In [1]:
import numpy as np

Numpy Basics

In [9]:
# Creation
a = np.array([1,2,3])
print(f"Array = {a}")
print(f"Number of dimensions = {a.ndim}")
print(f"Shape = {a.shape}")
print(f"Datatype = {a.dtype}")
print(f"Item size in bytes = {a.itemsize}")

Array = [1 2 3]
Number of dimensions = 1
Shape = (3,)
Datatype = int64
Item size in bytes = 8


In [10]:
# Properties of numpy array
a = np.array([[1,2,3], [3.2,4,5], [1,3,5.2]])
print(a)
print(f"Data type = {a.dtype}")
print(a.ndim)
print(a.shape)

[[1.  2.  3. ]
 [3.2 4.  5. ]
 [1.  3.  5.2]]
Data type = float64
2
(3, 3)


In [11]:
# Indexing
a = np.array([[1,2,3], [3,4,5], [1,3,5]])
print(a[0][2])
print(a[1,2])

3
5


In [12]:
#Get numbers from one row or one column
print(f"Numbers from 1st row = {a[0, :]}")
print(f"Numbers from 2nd column = {a[:, 1]}")

Numbers from 1st row = [1 2 3]
Numbers from 2nd column = [2 4 3]


In [13]:
# Sub matrix
b = a[1:3, 1:3]
b

array([[4, 5],
       [3, 5]])

In [14]:
# Get random rows or columns
b = a[:, [0,2]]
b

array([[1, 3],
       [3, 5],
       [1, 5]])

In [15]:
# Boolean masking
a = np.array([[4,1,6], [5,2,5], [7,10,11]])
b = a[a > 4]
b

array([ 6,  5,  5,  7, 10, 11])

In [16]:
b = a[(a > 2) & (a < 10)]
b

array([4, 6, 5, 5, 7])

Initialize a Numpy Array

In [18]:
zeros = np.zeros((3,2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
twos = np.full((3,4), 2)
twos

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [22]:
identity = np.identity(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# Create a random matrix with values between 0 and 1
random_3x2_matrix = np.random.rand(3,2)
print(f"Random 3x2 matrix: {random_3x2_matrix}")
random_3x2x2_matrix  = np.random.rand(3,2,2)
print(f"Random 3x2x2 matrix: {random_3x2x2_matrix}")

Random 3x2 matrix: [[0.28103216 0.20121355]
 [0.67302108 0.08843408]
 [0.45216747 0.47521063]]
Random 3x2x2 matrix: [[[0.49997952 0.37438971]
  [0.27907674 0.15603857]]

 [[0.95657195 0.95549178]
  [0.86340667 0.98781315]]

 [[0.01433675 0.51563082]
  [0.60607468 0.72689963]]]


In [25]:
# Create an even space distributed array
# 15 numbers
a = np.linspace(start = 1, stop = 10, num = 15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [28]:
# array with start and step positions
a = np.arange(start = 1, stop = 100, step = 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Reorganize Arrays

In [29]:
a = np.array([[1,2,3], [3,1,2]])
print(a)
print(a.shape)

[[1 2 3]
 [3 1 2]]
(2, 3)


In [30]:
b = a.reshape((3,2))
b

array([[1, 2],
       [3, 3],
       [1, 2]])

In [31]:
# Stack Different Arrays
a = np.array([[1,2,3], [2,3,4]])
b = np.array([[2,3,4], [5,1,6]])
print(a)
print(b)

[[1 2 3]
 [2 3 4]]
[[2 3 4]
 [5 1 6]]


In [32]:
# Vertical Stack
vertical_stack = np.vstack((a,b))
vertical_stack

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [5, 1, 6]])

In [33]:
# Horizontal Stack
horizontal_stack = np.hstack((a,b))
horizontal_stack

array([[1, 2, 3, 2, 3, 4],
       [2, 3, 4, 5, 1, 6]])

Mathematics

In [34]:
# Stats
a = np.array([[1,2,3], [2,3,1]])
print(f"Min = {np.min(a)}")
print(f"Max = {np.max(a)}")
print(f"Sum = {np.sum(a)}")
print(f"Mean = {np.mean(a)}")
print(f"Variance = {np.var(a)}")
print(f"Standard Deviation = {np.std(a)}")

Min = 1
Max = 3
Sum = 12
Mean = 2.0
Variance = 0.6666666666666666
Standard Deviation = 0.816496580927726


In [36]:
# Broadcasting
a = np.array([[1,2,3], [2,3,1]])
b = a + 1
list(b)

[array([2, 3, 4]), array([3, 4, 2])]

In [37]:
b = a - 2
b

array([[-1,  0,  1],
       [ 0,  1, -1]])

In [38]:
b = a * 4
b

array([[ 4,  8, 12],
       [ 8, 12,  4]])

In [39]:
# Broadcasting across multiple arrays
a = np.array([[1,2,3], [2,3,1],[4,2,3]])
b = np.array([[2,3,4]])
a+ b

array([[3, 5, 7],
       [4, 6, 5],
       [6, 5, 7]])

Linear Algebra

In [40]:
# Matrix multiplication
a = np.array([1,2,3])
b = np.array([3,4,2])
a * b

array([3, 8, 6])

In [41]:
# Dot product 
# 1x3 + 2x4 + 3x2
print(f"a.b = {a.dot(b)}")

a.b = 17


In [43]:
# Cross Product
a = np.array([[1,2,3], [4,1,2], [1,2,3]]) # 3x3
b = np.array([[3,4], [2,1], [5,1]]) # 3x2

# Note: column of a must be equal to row of b, columns must be same
print(f"a x b = {np.matmul(a,b)}")

a x b = [[22  9]
 [24 19]
 [22  9]]


In [46]:
# Determinant 
a = np.array([[1,2], [3,4]])
determinant = np.linalg.det(a)
print(determinant)

-2.0000000000000004


In [49]:
# Inverse Matrix
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)
print(f"Inverse of a = {b}")
print(f"Product = {np.matmul(a,b)}")

Inverse of a = [[-2.   1. ]
 [ 1.5 -0.5]]
Product = [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [50]:
# Diagonal Matrix
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
print(f"0th diagonal = {np.diag(x)}")
print(f"1st diagonal = {np.diag(x, k = 1)}")
print(f"2nd diagonal = {np.diag(x, k = 2)}")
print(f"-1st diagonal = {np.diag(x, k = -1)}")
print(f"-2nd diagonal = {np.diag(x, k = -2)}")

0th diagonal = [0 4 8]
1st diagonal = [1 5]
2nd diagonal = [2]
-1st diagonal = [3 7]
-2nd diagonal = [6]


Load Data to file

In [55]:
a = np.genfromtxt("/Users/neelalohithrkashyap/Documents/DataScience/Numpy/numbers.csv", delimiter=",")
a

array([[1.5, 2.1, 5.4, 6.1],
       [1.2, 3.1, 5.1, 5.1],
       [1. , 5.1, 5.1, 3.2]])

Speed Test with Lists

In [56]:
a = [i for i in range(1000000)]
b = np.arange(1000000)
import time

start = time.time() 
for i in range(len(a)): 
    a[i] += 1
end = time.time() 
print(f"Time to process Python list = {end - start}s")

start = time.time() 
b = b + 1
end = time.time() 
print(f"Time to process Numpy array = {end - start}s")

Time to process Python list = 0.08612608909606934s
Time to process Numpy array = 0.0018620491027832031s
